import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/dist/compiled/@next/font/dist/local";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


// import localFont from 'next/font/local';

// Load the font
// const sixtyfour = localFont({
//   src: "../../public/font/Sixtyfour-Regular-VariableFont_BLED,SCAN.ttf",
//   weight: '400', // Set the correct weight (optional)
//   style: 'normal', // Set the correct style (optional)
// });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          {children}
        </body>
    </html>
  );
}
